# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ApplePayPaymentDataType(object):

    """Implementation of the 'Apple Pay Payment Data Type' enum.

    Indicates the type of payment data passed, in case of Non China the
    payment data is 3DSECURE and for China it is EMV.

    Attributes:
        ENUM_3DSECURE: The enum member of type str.
        EMV: The enum member of type str.

    """
    ENUM_3DSECURE = '3DSECURE'

    EMV = 'EMV'

