# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AuthorizationIncompleteReason(object):

    """Implementation of the 'Authorization Incomplete Reason' enum.

    The reason why the authorized status is `PENDING`.

    Attributes:
        PENDING_REVIEW: The enum member of type str.
        DECLINED_BY_RISK_FRAUD_FILTERS: The enum member of type str.

    """
    PENDING_REVIEW = 'PENDING_REVIEW'

    DECLINED_BY_RISK_FRAUD_FILTERS = 'DECLINED_BY_RISK_FRAUD_FILTERS'

