# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AVSCode(object):

    """Implementation of the 'AVS Code' enum.

    The address verification code for Visa, Discover, Mastercard, or American
    Express transactions.

    Attributes:
        A: The enum member of type str.
        B: The enum member of type str.
        C: The enum member of type str.
        D: The enum member of type str.
        E: The enum member of type str.
        F: The enum member of type str.
        G: The enum member of type str.
        I: The enum member of type str.
        M: The enum member of type str.
        N: The enum member of type str.
        P: The enum member of type str.
        R: The enum member of type str.
        S: The enum member of type str.
        U: The enum member of type str.
        W: The enum member of type str.
        X: The enum member of type str.
        Y: The enum member of type str.
        Z: The enum member of type str.
        NULL: The enum member of type str.
        ENUM_0: The enum member of type str.
        ENUM_1: The enum member of type str.
        ENUM_2: The enum member of type str.
        ENUM_3: The enum member of type str.
        ENUM_4: The enum member of type str.

    """
    A = 'A'

    B = 'B'

    C = 'C'

    D = 'D'

    E = 'E'

    F = 'F'

    G = 'G'

    I = 'I'

    M = 'M'

    N = 'N'

    P = 'P'

    R = 'R'

    S = 'S'

    U = 'U'

    W = 'W'

    X = 'X'

    Y = 'Y'

    Z = 'Z'

    NULL = 'Null'

    ENUM_0 = '0'

    ENUM_1 = '1'

    ENUM_2 = '2'

    ENUM_3 = '3'

    ENUM_4 = '4'

