# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CaptureStatus(object):

    """Implementation of the 'Capture Status' enum.

    The status of the captured payment.

    Attributes:
        COMPLETED: The enum member of type str.
        DECLINED: The enum member of type str.
        PARTIALLY_REFUNDED: The enum member of type str.
        PENDING: The enum member of type str.
        REFUNDED: The enum member of type str.
        FAILED: The enum member of type str.

    """
    COMPLETED = 'COMPLETED'

    DECLINED = 'DECLINED'

    PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED'

    PENDING = 'PENDING'

    REFUNDED = 'REFUNDED'

    FAILED = 'FAILED'

