# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CaptureIncompleteReason(object):

    """Implementation of the 'Capture Incomplete Reason' enum.

    The reason why the captured payment status is `PENDING` or `DENIED`.

    Attributes:
        BUYER_COMPLAINT: The enum member of type str.
        CHARGEBACK: The enum member of type str.
        ECHECK: The enum member of type str.
        INTERNATIONAL_WITHDRAWAL: The enum member of type str.
        OTHER: The enum member of type str.
        PENDING_REVIEW: The enum member of type str.
        RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION: The enum member of type
            str.
        REFUNDED: The enum member of type str.
        TRANSACTION_APPROVED_AWAITING_FUNDING: The enum member of type str.
        UNILATERAL: The enum member of type str.
        VERIFICATION_REQUIRED: The enum member of type str.
        DECLINED_BY_RISK_FRAUD_FILTERS: The enum member of type str.

    """
    BUYER_COMPLAINT = 'BUYER_COMPLAINT'

    CHARGEBACK = 'CHARGEBACK'

    ECHECK = 'ECHECK'

    INTERNATIONAL_WITHDRAWAL = 'INTERNATIONAL_WITHDRAWAL'

    OTHER = 'OTHER'

    PENDING_REVIEW = 'PENDING_REVIEW'

    RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION = 'RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION'

    REFUNDED = 'REFUNDED'

    TRANSACTION_APPROVED_AWAITING_FUNDING = 'TRANSACTION_APPROVED_AWAITING_FUNDING'

    UNILATERAL = 'UNILATERAL'

    VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED'

    DECLINED_BY_RISK_FRAUD_FILTERS = 'DECLINED_BY_RISK_FRAUD_FILTERS'

