# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardVerificationMethod(object):

    """Implementation of the 'Card Verification Method' enum.

    The method used for card verification.

    Attributes:
        SCA_ALWAYS: The enum member of type str.
        SCA_WHEN_REQUIRED: The enum member of type str.
        ENUM_3D_SECURE: The enum member of type str.
        AVS_CVV: The enum member of type str.

    """
    SCA_ALWAYS = 'SCA_ALWAYS'

    SCA_WHEN_REQUIRED = 'SCA_WHEN_REQUIRED'

    ENUM_3D_SECURE = '3D_SECURE'

    AVS_CVV = 'AVS_CVV'

