# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardType(object):

    """Implementation of the 'Card Type' enum.

    Type of card. i.e Credit, Debit and so on.

    Attributes:
        CREDIT: The enum member of type str.
        DEBIT: The enum member of type str.
        PREPAID: The enum member of type str.
        STORE: The enum member of type str.
        UNKNOWN: The enum member of type str.

    """
    CREDIT = 'CREDIT'

    DEBIT = 'DEBIT'

    PREPAID = 'PREPAID'

    STORE = 'STORE'

    UNKNOWN = 'UNKNOWN'

