# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CheckoutPaymentIntent(object):

    """Implementation of the 'Checkout Payment Intent' enum.

    The intent to either capture payment immediately or authorize a payment
    for an order after order creation.

    Attributes:
        CAPTURE: The enum member of type str.
        AUTHORIZE: The enum member of type str.

    """
    CAPTURE = 'CAPTURE'

    AUTHORIZE = 'AUTHORIZE'

