# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CVVCode(object):

    """Implementation of the 'CVV Code' enum.

    The card verification value code for for Visa, Discover, Mastercard, or
    American Express.

    Attributes:
        E: The enum member of type str.
        I: The enum member of type str.
        M: The enum member of type str.
        N: The enum member of type str.
        P: The enum member of type str.
        S: The enum member of type str.
        U: The enum member of type str.
        X: The enum member of type str.
        ENUM_ALL OTHERS: The enum member of type str.
        ENUM_0: The enum member of type str.
        ENUM_1: The enum member of type str.
        ENUM_2: The enum member of type str.
        ENUM_3: The enum member of type str.
        ENUM_4: The enum member of type str.

    """
    E = 'E'

    I = 'I'

    M = 'M'

    N = 'N'

    P = 'P'

    S = 'S'

    U = 'U'

    X = 'X'

    ENUM_ALL_OTHERS = 'All others'

    ENUM_0 = '0'

    ENUM_1 = '1'

    ENUM_2 = '2'

    ENUM_3 = '3'

    ENUM_4 = '4'

