# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DisbursementMode(object):

    """Implementation of the 'Disbursement Mode' enum.

    The funds that are held on behalf of the merchant.

    Attributes:
        INSTANT: The enum member of type str.
        DELAYED: The enum member of type str.

    """
    INSTANT = 'INSTANT'

    DELAYED = 'DELAYED'

