# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EnrollmentStatus(object):

    """Implementation of the 'Enrollment Status' enum.

    Status of Authentication eligibility.

    Attributes:
        Y: The enum member of type str.
        N: The enum member of type str.
        U: The enum member of type str.
        B: The enum member of type str.

    """
    Y = 'Y'

    N = 'N'

    U = 'U'

    B = 'B'

