# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FullfillmentType(object):

    """Implementation of the 'Fullfillment Type' enum.

    A classification for the method of purchase fulfillment (e.g shipping,
    in-store pickup, etc). Either `type` or `options` may be present, but not
    both.

    Attributes:
        SHIPPING: The enum member of type str.
        PICKUP_IN_PERSON: The enum member of type str.
        PICKUP_IN_STORE: The enum member of type str.
        PICKUP_FROM_PERSON: The enum member of type str.

    """
    SHIPPING = 'SHIPPING'

    PICKUP_IN_PERSON = 'PICKUP_IN_PERSON'

    PICKUP_IN_STORE = 'PICKUP_IN_STORE'

    PICKUP_FROM_PERSON = 'PICKUP_FROM_PERSON'

