# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GooglePayAuthenticationMethod(object):

    """Implementation of the 'Google Pay Authentication Method' enum.

    Authentication Method which is used for the card transaction.

    Attributes:
        PAN_ONLY: The enum member of type str.
        CRYPTOGRAM_3DS: The enum member of type str.

    """
    PAN_ONLY = 'PAN_ONLY'

    CRYPTOGRAM_3DS = 'CRYPTOGRAM_3DS'

