# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ItemCategory(object):

    """Implementation of the 'Item Category' enum.

    The item category type.

    Attributes:
        DIGITAL_GOODS: The enum member of type str.
        PHYSICAL_GOODS: The enum member of type str.
        DONATION: The enum member of type str.

    """
    DIGITAL_GOODS = 'DIGITAL_GOODS'

    PHYSICAL_GOODS = 'PHYSICAL_GOODS'

    DONATION = 'DONATION'

