# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LiabilityShiftIndicator(object):

    """Implementation of the 'Liability Shift Indicator' enum.

    Liability shift indicator. The outcome of the issuer's authentication.

    Attributes:
        NO: The enum member of type str.
        POSSIBLE: The enum member of type str.
        UNKNOWN: The enum member of type str.

    """
    NO = 'NO'

    POSSIBLE = 'POSSIBLE'

    UNKNOWN = 'UNKNOWN'

