# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderStatus(object):

    """Implementation of the 'Order Status' enum.

    The order status.

    Attributes:
        CREATED: The enum member of type str.
        SAVED: The enum member of type str.
        APPROVED: The enum member of type str.
        VOIDED: The enum member of type str.
        COMPLETED: The enum member of type str.
        PAYER_ACTION_REQUIRED: The enum member of type str.

    """
    CREATED = 'CREATED'

    SAVED = 'SAVED'

    APPROVED = 'APPROVED'

    VOIDED = 'VOIDED'

    COMPLETED = 'COMPLETED'

    PAYER_ACTION_REQUIRED = 'PAYER_ACTION_REQUIRED'

