# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PatchOp(object):

    """Implementation of the 'Patch Op' enum.

    The operation.

    Attributes:
        ADD: The enum member of type str.
        REMOVE: The enum member of type str.
        REPLACE: The enum member of type str.
        MOVE: The enum member of type str.
        COPY: The enum member of type str.
        TEST: The enum member of type str.

    """
    ADD = 'add'

    REMOVE = 'remove'

    REPLACE = 'replace'

    MOVE = 'move'

    COPY = 'copy'

    TEST = 'test'

