# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PayPalExperienceUserAction(object):

    """Implementation of the 'PayPal Experience User Action' enum.

    Configures a <strong>Continue</strong> or <strong>Pay Now</strong>
    checkout flow.

    Attributes:
        CONTINUE: The enum member of type str.
        PAY_NOW: The enum member of type str.

    """
    CONTINUE = 'CONTINUE'

    PAY_NOW = 'PAY_NOW'

