# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PayeePaymentMethodPreference(object):

    """Implementation of the 'Payee Payment Method Preference' enum.

    The merchant-preferred payment methods.

    Attributes:
        UNRESTRICTED: The enum member of type str.
        IMMEDIATE_PAYMENT_REQUIRED: The enum member of type str.

    """
    UNRESTRICTED = 'UNRESTRICTED'

    IMMEDIATE_PAYMENT_REQUIRED = 'IMMEDIATE_PAYMENT_REQUIRED'

