# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PaymentAdviceCode(object):

    """Implementation of the 'Payment Advice Code' enum.

    The declined payment transactions might have payment advice codes. The
    card networks, like Visa and Mastercard, return payment advice codes.

    Attributes:
        ENUM_01: The enum member of type str.
        ENUM_02: The enum member of type str.
        ENUM_03: The enum member of type str.
        ENUM_21: The enum member of type str.

    """
    ENUM_01 = '01'

    ENUM_02 = '02'

    ENUM_03 = '03'

    ENUM_21 = '21'

