# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProcessingInstruction(object):

    """Implementation of the 'Processing Instruction' enum.

    The instruction to process an order.

    Attributes:
        ORDER_COMPLETE_ON_PAYMENT_APPROVAL: The enum member of type str.
        NO_INSTRUCTION: The enum member of type str.

    """
    ORDER_COMPLETE_ON_PAYMENT_APPROVAL = 'ORDER_COMPLETE_ON_PAYMENT_APPROVAL'

    NO_INSTRUCTION = 'NO_INSTRUCTION'

