# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RefundStatus(object):

    """Implementation of the 'Refund Status' enum.

    The status of the refund.

    Attributes:
        CANCELLED: The enum member of type str.
        FAILED: The enum member of type str.
        PENDING: The enum member of type str.
        COMPLETED: The enum member of type str.

    """
    CANCELLED = 'CANCELLED'

    FAILED = 'FAILED'

    PENDING = 'PENDING'

    COMPLETED = 'COMPLETED'

