# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SellerProtectionStatus(object):

    """Implementation of the 'Seller Protection Status' enum.

    Indicates whether the transaction is eligible for seller protection. For
    information, see [PayPal Seller Protection for
    Merchants](https://www.paypal.com/us/webapps/mpp/security/seller-protection
    ).

    Attributes:
        ELIGIBLE: The enum member of type str.
        PARTIALLY_ELIGIBLE: The enum member of type str.
        NOT_ELIGIBLE: The enum member of type str.

    """
    ELIGIBLE = 'ELIGIBLE'

    PARTIALLY_ELIGIBLE = 'PARTIALLY_ELIGIBLE'

    NOT_ELIGIBLE = 'NOT_ELIGIBLE'

