# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ShippingType(object):

    """Implementation of the 'Shipping Type' enum.

    A classification for the method of purchase fulfillment.

    Attributes:
        SHIPPING: The enum member of type str.
        PICKUP: The enum member of type str.
        PICKUP_IN_STORE: The enum member of type str.
        PICKUP_FROM_PERSON: The enum member of type str.

    """
    SHIPPING = 'SHIPPING'

    PICKUP = 'PICKUP'

    PICKUP_IN_STORE = 'PICKUP_IN_STORE'

    PICKUP_FROM_PERSON = 'PICKUP_FROM_PERSON'

