# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StoredPaymentSourcePaymentType(object):

    """Implementation of the 'Stored Payment Source Payment Type' enum.

    Indicates the type of the stored payment_source payment.

    Attributes:
        ONE_TIME: The enum member of type str.
        RECURRING: The enum member of type str.
        UNSCHEDULED: The enum member of type str.

    """
    ONE_TIME = 'ONE_TIME'

    RECURRING = 'RECURRING'

    UNSCHEDULED = 'UNSCHEDULED'

