# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TaxIdType(object):

    """Implementation of the 'Tax Id Type' enum.

    The customer's tax ID type.

    Attributes:
        BR_CPF: The enum member of type str.
        BR_CNPJ: The enum member of type str.

    """
    BR_CPF = 'BR_CPF'

    BR_CNPJ = 'BR_CNPJ'

