# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TokenType(object):

    """Implementation of the 'Token Type' enum.

    The tokenization method that generated the ID.

    Attributes:
        BILLING_AGREEMENT: The enum member of type str.

    """
    BILLING_AGREEMENT = 'BILLING_AGREEMENT'

