# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UPCType(object):

    """Implementation of the 'UPC Type' enum.

    The Universal Product Code type.

    Attributes:
        UPCA: The enum member of type str.
        UPCB: The enum member of type str.
        UPCC: The enum member of type str.
        UPCD: The enum member of type str.
        UPCE: The enum member of type str.
        UPC2: The enum member of type str.
        UPC5: The enum member of type str.

    """
    UPCA = 'UPC-A'

    UPCB = 'UPC-B'

    UPCC = 'UPC-C'

    UPCD = 'UPC-D'

    UPCE = 'UPC-E'

    UPC2 = 'UPC-2'

    UPC5 = 'UPC-5'

