# -*- coding: utf-8 -*-

"""
paypalrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class VenmoPaymentTokenUsageType(object):

    """Implementation of the 'Venmo Payment Token Usage Type' enum.

    The usage type associated with the Venmo payment token.

    Attributes:
        MERCHANT: The enum member of type str.
        PLATFORM: The enum member of type str.

    """
    MERCHANT = 'MERCHANT'

    PLATFORM = 'PLATFORM'

